# Aplikasi KAL

**PageRank**


PageRank adalah sebuah algoritma yang dikembangkan oleh Larry Page dan Sergey Brin, pendiri Google, untuk menilai dan merangking halaman web berdasarkan pentingnya. Algoritma ini didasarkan pada struktur tautan (link) dari web, dengan asumsi bahwa halaman web yang lebih penting akan lebih banyak ditautkan oleh halaman web lainnya

**konsep Dasar PageRank**

* Tautan Sebagai Suara:

Setiap tautan dari satu halaman web ke halaman web lain dianggap sebagai suara. Namun, tidak semua suara memiliki bobot yang sama. Suara dari halaman yang lebih penting dihitung lebih besar daripada suara dari halaman yang kurang penting.

* Distribusi Nilai PageRank:

Nilai PageRank dari sebuah halaman didistribusikan ke halaman-halaman yang ditautkannya. Sebagai contoh, jika halaman A memiliki PageRank tinggi dan menautkan ke halaman B, maka halaman B akan mendapatkan peningkatan nilai PageRank.

* Iterasi PageRank:

PageRank dihitung secara iteratif. Dimulai dengan memberikan nilai awal yang sama ke setiap halaman, kemudian nilai-nilai ini diperbarui berulang kali berdasarkan tautan-tautan antar halaman hingga nilai PageRank konvergen

**Rumus PageRank**


Rumus dasar untuk menghitung PageRank
𝑃𝑅
(𝐴)
dari halaman A adalah sebagai berikut:

$PR(A) = (1 - d) + d \left( \sum_{i=1}^n \frac{PR(T_i)}{C(T_i)} \right)$

* $PR(A)$: PageRank dari halaman A

* 𝑑: Damping factor, biasanya sekitar 0.85, yang merepresentasikan kemungkinan pengguna melanjutkan penelusuran ke tautan berikutnya daripada memulai pencarian baru

* $T i$
 : Halaman-halaman yang menautkan ke halaman A

* $PR(Ti​)$: PageRank dari halaman
𝑇𝑖

* $C(Ti)$: Jumlah tautan keluar (outbound links) dari halaman
𝑇𝑖
​


**Proses iterasi**

1.Inisialisasi:

Semua halaman diberikan nilai PageRank awal yang sama, misalnya 1.

2.Perbarui Nilai PageRank:

Gunakan rumus di atas untuk memperbarui nilai PageRank setiap halaman berdasarkan PageRank halaman-halaman yang menautkannya.

3.Konvergensi:

Ulangi langkah 2 sampai nilai PageRank semua halaman berubah sangat kecil atau mencapai tingkat konvergensi yang ditentukan.



## Implementasi PageRank

* Random Walk (Jalan acak)

Web dapat direpresentasikan seperti grafik berarah
di mana node mewakili halaman web dan tepinya membentuk hubungan di antara keduanya.
Biasanya, jika sebuah node (halaman web)Sayaterhubung ke sebuah nodeJ, itu artinyaSayamengacu padaJ.

$A --> B
A --> C
B --> D
C --> D
D --> A
$


Kita harus mendefinisikan apa pentingnya halaman web. Sebagai pendekatan pertama, kita dapat mengatakan bahwa ini adalah jumlah total halaman web yang merujuk padanya. Jika kita berhenti pada kriteria ini, pentingnya halaman web yang merujuk padanya tidak diperhitungkan. Dengan kata lain, halaman web yang penting dan halaman yang kurang penting memiliki bobot yang sama. Pendekatan lain adalah dengan berasumsi bahwa suatu halaman web menyebarkan kepentingannya secara merata ke semua halaman web yang ditautkannya. Dengan melakukan itu, kita kemudian dapat menentukan skor dari sebuah node j sebagai berikut:  
$$r_j = \sum_{i \rightarrow j} \frac{r_i}{d_i}$$

dimana rᵢ adalah skor dari node i dan dᵢ derajat keluarnya  




Dari contoh di atas, kita dapat menulis sistem linier berikut.

$\begin{cases}
r_0 = \frac{r_4}{3} \\
r_1 = \frac{r_2}{2} + \frac{r_4}{3} + r_3 \\
r_2 = \frac{r_0}{3} + \frac{r_4}{3} \\
r_3 = \frac{r_2}{2} + \frac{r_0}{3} \\
r_4 = \frac{r_0}{3} + r_1
\end{cases}
$

* implementasi hitung manual

In [3]:
import numpy as np

In [4]:
A = np.array ([[0,0,1,1/2],[1/3,0,0,0],[1/3,1/2,0,1/2],[1/3,1/2,0,0]])
V0 = np.array ([[0.25],[0.25],[0.25],[0.25]])
V1 = A@V0
print(V1)
V2 = A@V1
print(V2)
V3 = A@V2
print(V3)
V4 = A@V3
print(V4)
V5 = A@V4
print(V5)
V6 = A@V5
print(V6)
V7 = A@V6
print(V7)
V8 = A@V7
print(V8)
V0 = np.array ([[0.3],[0.2],[0.3],[0.2]])
V1 = A@V0
print(V1)
V2 = A@V1
print(V2)
V3 = A@V2
print(V3)
V4 = A@V3
print(V4)
V5 = A@V4
print(V5)
V6 = A@V5
print(V6)
V7 = A@V6
print(V7)
V8 =A@V7
print(V8)


[[0.375     ]
 [0.08333333]
 [0.33333333]
 [0.20833333]]
[[0.4375    ]
 [0.125     ]
 [0.27083333]
 [0.16666667]]
[[0.35416667]
 [0.14583333]
 [0.29166667]
 [0.20833333]]
[[0.39583333]
 [0.11805556]
 [0.29513889]
 [0.19097222]]
[[0.390625  ]
 [0.13194444]
 [0.28645833]
 [0.19097222]]
[[0.38194444]
 [0.13020833]
 [0.29166667]
 [0.19618056]]
[[0.38975694]
 [0.12731481]
 [0.29050926]
 [0.19241898]]
[[0.38671875]
 [0.12991898]
 [0.28978588]
 [0.19357639]]
[[0.4]
 [0.1]
 [0.3]
 [0.2]]
[[0.4       ]
 [0.13333333]
 [0.28333333]
 [0.18333333]]
[[0.375     ]
 [0.13333333]
 [0.29166667]
 [0.2       ]]
[[0.39166667]
 [0.125     ]
 [0.29166667]
 [0.19166667]]
[[0.3875    ]
 [0.13055556]
 [0.28888889]
 [0.19305556]]
[[0.38541667]
 [0.12916667]
 [0.29097222]
 [0.19444444]]
[[0.38819444]
 [0.12847222]
 [0.29027778]
 [0.19305556]]
[[0.38680556]
 [0.12939815]
 [0.29016204]
 [0.19363426]]


* implementasi code

In [5]:
A = np.array ([[0.3],[0.2],[0.3],[0.2]])
print(f'matrik A:{A}')

jumlah_matriks = 5

toleransi = 0.05
def hitung_error(matriks1, matriks2):
    error_absolut = np.abs(matriks1 - matriks2)
    error_relatif = np.abs((matriks1 - matriks2) / matriks1)
    return error_absolut, error_relatif

for i in range(jumlah_matriks):
    matriks_acak = np.random.uniform([[0.25],[0.25],[0.25],[0.25]])
    print(f'matrik acak:{matriks_acak}')

    # Menghitung error
    error_absolut, error_relatif = hitung_error(A, matriks_acak)

    within_tolerance = error_relatif < toleransi

    print()
    print(f"Matriks {i+1}:")
    print("Matriks Acak:", matriks_acak)
    print("Error Absolut:", error_absolut)
    print("Error Relatif:", error_relatif)
    print("Within Tolerance:", within_tolerance)
    print()

matrik A:[[0.3]
 [0.2]
 [0.3]
 [0.2]]
matrik acak:[[0.62691801]
 [0.38274397]
 [0.84808585]
 [0.40335923]]

Matriks 1:
Matriks Acak: [[0.62691801]
 [0.38274397]
 [0.84808585]
 [0.40335923]]
Error Absolut: [[0.32691801]
 [0.18274397]
 [0.54808585]
 [0.20335923]]
Error Relatif: [[1.08972672]
 [0.91371986]
 [1.82695283]
 [1.01679616]]
Within Tolerance: [[False]
 [False]
 [False]
 [False]]

matrik acak:[[0.41606923]
 [0.66311976]
 [0.90452849]
 [0.48605658]]

Matriks 2:
Matriks Acak: [[0.41606923]
 [0.66311976]
 [0.90452849]
 [0.48605658]]
Error Absolut: [[0.11606923]
 [0.46311976]
 [0.60452849]
 [0.28605658]]
Error Relatif: [[0.38689744]
 [2.3155988 ]
 [2.01509497]
 [1.4302829 ]]
Within Tolerance: [[False]
 [False]
 [False]
 [False]]

matrik acak:[[0.64510626]
 [0.27957317]
 [0.56833422]
 [0.27538922]]

Matriks 3:
Matriks Acak: [[0.64510626]
 [0.27957317]
 [0.56833422]
 [0.27538922]]
Error Absolut: [[0.34510626]
 [0.07957317]
 [0.26833422]
 [0.07538922]]
Error Relatif: [[1.15035419]
 [0.3