##DETERMINAN##


1. Definisi Determinan:
Determinan adalah suatu fungsi yang didefinisikan untuk matriks persegi.
Untuk matriks
𝐴
A berukuran
𝑛
×
𝑛
n×n, determinan diwakili dengan
det
(
𝐴
)
det(A).

2. Sifat-Sifat Determinan:

a. Properti Dasar:
- Determinan Matriks Identitas:
det
(
𝐼
)
=
1
det(I)=1
- Pertukaran Baris: Ketika dua baris matriks ditukar, tanda determinan berubah.
- Pengalikan Baris dengan Skalar: Jika satu baris matriks dikalikan dengan skalar
𝑘
k, determinan juga dikalikan dengan
𝑘
k.

In [1]:
import numpy as np

# Properti Dasar
# 1. Determinan Matriks Identitas
identity_matrix = np.identity(3)
det_identity = np.linalg.det(identity_matrix)
print("Determinan Matriks Identitas:")
print(det_identity)

# 2. Pertukaran Baris
matrix1 = np.array([[1, 2, 3],
                    [4, 5, 6],
                    [7, 8, 9]])
matrix2 = np.array([[4, 5, 6],
                    [1, 2, 3],
                    [7, 8, 9]])
det_matrix1 = np.linalg.det(matrix1)
det_matrix2 = np.linalg.det(matrix2)
print("\nDeterminan Matriks Awal:")
print(det_matrix1)
print("Determinan Matriks Setelah Pertukaran Baris:")
print(det_matrix2)

# 3. Pengalikan Baris dengan Skalar
scalar = 2
matrix3 = np.array([[1, 2, 3],
                    [4, 5, 6],
                    [7, 8, 9]])
matrix4 = matrix3 * scalar
det_matrix3 = np.linalg.det(matrix3)
det_matrix4 = np.linalg.det(matrix4)
print("\nDeterminan Matriks Awal:")
print(det_matrix3)
print("Determinan Matriks Setelah Pengalikan Baris dengan Skalar:")
print(det_matrix4)

Determinan Matriks Identitas:
1.0

Determinan Matriks Awal:
0.0
Determinan Matriks Setelah Pertukaran Baris:
0.0

Determinan Matriks Awal:
0.0
Determinan Matriks Setelah Pengalikan Baris dengan Skalar:
0.0


b. Properti Terkait Operasi Matriks:
- Penjumlahan Matriks: Determinan dari hasil penjumlahan dua matriks adalah penjumlahan determinan masing-masing matriks.
- Perkalian Matriks: Determinan dari hasil perkalian dua matriks adalah perkalian determinan masing-masing matriks.
- Transpos Matriks: Determinan matriks transpos sama dengan determinan matriks aslinya.

In [2]:
# Properti Terkait Operasi Matriks
# 1. Penjumlahan Matriks
matrix5 = np.array([[1, 2],
                    [3, 4]])
matrix6 = np.array([[5, 6],
                    [7, 8]])
matrix_sum = matrix5 + matrix6
det_matrix_sum = np.linalg.det(matrix_sum)
det_matrix5 = np.linalg.det(matrix5)
det_matrix6 = np.linalg.det(matrix6)
print("\nDeterminan Matriks Pertama:")
print(det_matrix5)
print("Determinan Matriks Kedua:")
print(det_matrix6)
print("Determinan Hasil Penjumlahan Matriks:")
print(det_matrix_sum)

# 2. Perkalian Matriks
matrix7 = np.array([[1, 2],
                    [3, 4]])
matrix8 = np.array([[5, 6],
                    [7, 8]])
matrix_product = np.dot(matrix7, matrix8)
det_matrix_product = np.linalg.det(matrix_product)
det_matrix7 = np.linalg.det(matrix7)
det_matrix8 = np.linalg.det(matrix8)
print("\nDeterminan Matriks Pertama:")
print(det_matrix7)
print("Determinan Matriks Kedua:")
print(det_matrix8)
print("Determinan Hasil Perkalian Matriks:")
print(det_matrix_product)

# 3. Transpos Matriks
matrix9 = np.array([[1, 2],
                    [3, 4]])
matrix_transpose = np.transpose(matrix9)
det_matrix9 = np.linalg.det(matrix9)
det_matrix_transpose = np.linalg.det(matrix_transpose)
print("\nDeterminan Matriks Awal:")
print(det_matrix9)
print("Determinan Matriks Transpos:")
print(det_matrix_transpose)


Determinan Matriks Pertama:
-2.0000000000000004
Determinan Matriks Kedua:
-2.000000000000005
Determinan Hasil Penjumlahan Matriks:
-7.999999999999991

Determinan Matriks Pertama:
-2.0000000000000004
Determinan Matriks Kedua:
-2.000000000000005
Determinan Hasil Perkalian Matriks:
4.000000000000008

Determinan Matriks Awal:
-2.0000000000000004
Determinan Matriks Transpos:
-2.0


c.untuk menukar baris atau kolom pada matriks dan menghitung determinannya:

In [3]:
import numpy as np

# Matriks contoh
A = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])

# Fungsi untuk menukar dua baris pada matriks
def swap_rows(matrix, row1, row2):
    matrix[[row1, row2]] = matrix[[row2, row1]]

# Fungsi untuk menukar dua kolom pada matriks
def swap_columns(matrix, col1, col2):
    matrix[:, [col1, col2]] = matrix[:, [col2, col1]]

# Cetak matriks awal dan determinannya
print("Matriks Awal:")
print(A)
print("Determinan Awal:", np.linalg.det(A))

# Menukar baris ke-1 dan ke-2
swap_rows(A, 0, 1)
print("\nSetelah Menukar Baris 1 dan 2:")
print(A)
print("Determinan Setelah Menukar Baris 1 dan 2:", np.linalg.det(A))

# Menukar kolom ke-0 dan ke-2
swap_columns(A, 0, 2)
print("\nSetelah Menukar Kolom 0 dan 2:")
print(A)
print("Determinan Setelah Menukar Kolom 0 dan 2:", np.linalg.det(A))


Matriks Awal:
[[1 2 3]
 [4 5 6]
 [7 8 9]]
Determinan Awal: 0.0

Setelah Menukar Baris 1 dan 2:
[[4 5 6]
 [1 2 3]
 [7 8 9]]
Determinan Setelah Menukar Baris 1 dan 2: 0.0

Setelah Menukar Kolom 0 dan 2:
[[6 5 4]
 [3 2 1]
 [9 8 7]]
Determinan Setelah Menukar Kolom 0 dan 2: 0.0


##MATRIKS SEGITIGA

nilai determinan dari matriks segitiga atas dan bawah sesuai dengan aturan bahwa determinan dari matriks segitiga adalah hasil perkalian dari elemen-elemen diagonal utamanya

In [5]:
import numpy as np

# Matriks segitiga atas contoh
A = np.array([[1, 2, 3],
              [0, 4, 5],
              [0, 0, 6]])

# Matriks segitiga bawah contoh
B = np.array([[1, 0, 0],
              [4, 5, 0],
              [7, 8, 9]])

# Fungsi untuk mencetak matriks segitiga beserta determinannya
def print_triangular_matrix(matrix):
    rows, cols = matrix.shape
    for i in range(rows):
        for j in range(cols):
            if j < i:
                print("0", end="\t")
            else:
                print(matrix[i, j], end="\t")
        print()
    print("Determinan:", np.prod(np.diagonal(matrix)))

# Cetak matriks segitiga atas dan determinannya
print("Matriks Segitiga Atas:")
print_triangular_matrix(A)

# Cetak matriks segitiga bawah dan determinannya
print("\nMatriks Segitiga Bawah:")
print_triangular_matrix(B)


Matriks Segitiga Atas:
1	2	3	
0	4	5	
0	0	6	
Determinan: 24

Matriks Segitiga Bawah:
1	0	0	
0	5	0	
0	0	9	
Determinan: 45


##Metode ekspansi kofaktor

adalah salah satu cara untuk menghitung determinan dari matriks persegi. Metode ini melibatkan dekomposisi matriks menjadi matriks minor dan matriks kofaktor.

Mari kita jelaskan langkah-langkahnya dengan lebih detail:

Pilih Baris atau Kolom: Pertama, kita memilih baris atau kolom dari matriks yang akan kita gunakan untuk menghitung determinan. Pilihan ini bisa sesuai dengan preferensi atau kebutuhan perhitungan.
Ekspansi: Setelah baris atau kolom dipilih, kita ekspansi matriks tersebut dengan menggunakan kofaktor. Ini berarti setiap elemen dalam baris atau kolom tersebut akan dikalikan dengan kofaktornya yang sesuai.
Kofaktor: Kofaktor dari setiap elemen adalah determinan dari matriks minor yang dihasilkan dengan menghapus baris dan kolom yang berisi elemen tersebut, dikalikan dengan faktor penentu yang sesuai. Faktor penentu ini adalah (-1)^(i+j) di mana i dan j adalah indeks baris dan kolom dari elemen tersebut.
Determinan: Setelah mengalikan setiap elemen dengan kofaktornya masing-masing, kita menjumlahkan hasilnya. Ini akan menghasilkan nilai determinan dari matriks.

In [6]:
import numpy as np

# Fungsi untuk menghitung matriks kofaktor
def cofactor_matrix(matrix):
    rows, cols = matrix.shape
    cofactor_mat = np.zeros((rows, cols))
    for i in range(rows):
        for j in range(cols):
            minor = np.delete(np.delete(matrix, i, axis=0), j, axis=1)
            cofactor_mat[i, j] = (-1) ** (i + j) * np.linalg.det(minor)
    return cofactor_mat

# Fungsi untuk menghitung determinan dari matriks menggunakan kofaktor
def determinant_with_cofactor(matrix):
    cofactors = cofactor_matrix(matrix)
    det = np.sum(matrix[0] * cofactors[0])
    return det

# Matriks contoh
A = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])

# Hitung determinan menggunakan kofaktor
determinant = determinant_with_cofactor(A)
print("Determinan menggunakan kofaktor:", determinant)


Determinan menggunakan kofaktor: 0.0
